using System;
using System.IO;
using PathManager.Core.Catalog;
using PathManager.Core.Env;
using PathManager.Core.Exceptions;

namespace PathManager.Core.Complete;

public class CompletionManager
{
    private readonly IEnvironmentProvider _env;
    private readonly ICommandRunner _runner;
    private readonly string _completionsDir;

    public string CompletionsDirectory => _completionsDir;

    public CompletionManager(IEnvironmentProvider env, ICommandRunner? commandRunner = null)
    {
        _env = env ?? throw new ArgumentNullException(nameof(env));
        _runner = commandRunner ?? new PowerShellCommandRunner();
        _completionsDir = Path.Combine(_env.GetPmHome(), "completions");
        Directory.CreateDirectory(_completionsDir);
    }

    public string GetHookScript()
    {
        var pmHome = _env.GetPmHome();
        var shimsDir = Path.Combine(pmHome, "shims");
        var compsDir = _completionsDir;

        return $@"# >>> PathManager Initialization >>>
# Automatically generated by PathManager. Do not edit manually.
$pmShimDir = ""{shimsDir}""
if (Test-Path $pmShimDir) {{
    if ($env:PATH -notlike ""$pmShimDir;*"") {{
        $env:PATH = ""$pmShimDir;$env:PATH""
    }}
}}

$pmCompDir = ""{compsDir}""
if (Test-Path $pmCompDir) {{
    Get-ChildItem -Path $pmCompDir -Filter ""*.ps1"" -File -ErrorAction SilentlyContinue | ForEach-Object {{
        . $_.FullName
    }}
}}

# Native Argument Completer for pathman CLI
if (Get-Command Register-ArgumentCompleter -ErrorAction SilentlyContinue) {{
    Register-ArgumentCompleter -Native -CommandName pathman -ScriptBlock {{
        param($wordToComplete, $commandAst, $cursorPosition)
        $elements = $commandAst.CommandElements
        $verbs = @('link', 'unlink', 'list', 'why', 'doctor', 'path', 'undo', 'completions', 'uninstall', 'upgrade')
        $flags = @('--json', '--help', '-h', '--version', '-v')

        if ($elements.Count -le 2) {{
            return ($verbs + $flags) | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }}
        }}

        $verb = $elements[1].Value
        switch ($verb) {{
            'link' {{
                $linkFlags = @('--force', '--host', '--i-trust-this', '--json')
                return $linkFlags | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'path' {{
                $pathSub = @('add', 'remove')
                return $pathSub | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'doctor' {{
                $docFlags = @('--repair', '--json')
                return $docFlags | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'completions' {{
                if ($elements.Count -le 3) {{
                    $compSub = @('install', 'register-file', 'register-command', 'from-help')
                    return $compSub | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                        [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                    }}
                }}
                $compFlags = @('--name', '--force', '--json', '--windows-powershell')
                return $compFlags | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'uninstall' {{
                $unFlags = @('--keep-shims', '--json')
                return $unFlags | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
        }}
    }}
}}
# <<< PathManager Initialization <<<
";
    }

    public string InstallHook(bool windowsPowerShell = false)
    {
        var userProfile = _env.GetUserProfile();
        var profileDir = windowsPowerShell
            ? Path.Combine(userProfile, "Documents", "WindowsPowerShell")
            : Path.Combine(userProfile, "Documents", "PowerShell");

        var profilePath = Path.Combine(profileDir, "Microsoft.PowerShell_profile.ps1");
        var hook = GetHookScript();

        try
        {
            Directory.CreateDirectory(profileDir);

            var existingContent = File.Exists(profilePath) ? File.ReadAllText(profilePath) : "";
            if (existingContent.Contains("# >>> PathManager Initialization >>>"))
            {
                // Replace existing block
                var startIdx = existingContent.IndexOf("# >>> PathManager Initialization >>>", StringComparison.Ordinal);
                var endMarker = "# <<< PathManager Initialization <<<";
                var endIdx = existingContent.IndexOf(endMarker, StringComparison.Ordinal);
                if (endIdx != -1)
                {
                    endIdx += endMarker.Length;
                    existingContent = existingContent.Remove(startIdx, endIdx - startIdx).Trim();
                }
            }

            var updatedContent = string.IsNullOrWhiteSpace(existingContent)
                ? hook
                : existingContent.TrimEnd() + System.Environment.NewLine + System.Environment.NewLine + hook;

            File.WriteAllText(profilePath, updatedContent);
            return profilePath;
        }
        catch (Exception ex)
        {
            throw new ProfileWriteFailedException(profilePath, hook, ex);
        }
    }

    public void AddCompletionFile(string commandName, string scriptContent)
    {
        RegisterScript(commandName, scriptContent, force: true);
    }

    public bool RemoveCompletionFile(string commandName)
    {
        var path = Path.Combine(_completionsDir, commandName + ".ps1");
        if (File.Exists(path))
        {
            File.Delete(path);
            return true;
        }
        return false;
    }

    public string RegisterFile(string sourcePath, string? commandName = null, bool force = false)
    {
        if (string.IsNullOrWhiteSpace(sourcePath) || !File.Exists(sourcePath))
        {
            throw new CompleterFileNotFoundException(sourcePath ?? "");
        }

        if (!string.Equals(Path.GetExtension(sourcePath), ".ps1", StringComparison.OrdinalIgnoreCase))
        {
            throw new CompleterUnsupportedFileException(sourcePath);
        }

        var name = string.IsNullOrWhiteSpace(commandName)
            ? Path.GetFileNameWithoutExtension(sourcePath)
            : commandName;
        var content = File.ReadAllText(sourcePath);
        return RegisterScript(name, content, force);
    }

    public string RegisterFromCommand(string commandLine, string? commandName = null, bool force = false)
    {
        if (string.IsNullOrWhiteSpace(commandLine))
        {
            throw new CompleterEmptyException("No command was provided to generate a completion script.");
        }

        var result = _runner.Run(commandLine, TimeSpan.FromSeconds(30));
        if (result.ExitCode != 0)
        {
            throw new CompleterCommandFailedException(commandLine, result.ExitCode, result.StandardError);
        }

        var name = string.IsNullOrWhiteSpace(commandName) ? InferCommandName(commandLine) : commandName;
        return RegisterScript(name, result.StandardOutput, force);
    }

    public string RegisterFromHelp(string commandLine, string? commandName = null, bool force = false)
    {
        if (string.IsNullOrWhiteSpace(commandLine))
        {
            throw new CompleterEmptyException("No command was provided to parse --help from.");
        }

        var name = string.IsNullOrWhiteSpace(commandName) ? InferCommandName(commandLine) : commandName;
        var helpText = CaptureHelpText(commandLine);
        var script = HelpCompleterGenerator.Generate(name, helpText);
        return RegisterScript(name, script, force);
    }

    public string RegisterScript(string commandName, string scriptContent, bool force = false)
    {
        CatalogManager.ValidateCommandName(commandName);

        if (string.IsNullOrWhiteSpace(scriptContent))
        {
            throw new CompleterEmptyException($"Completion script for '{commandName}' was empty.");
        }

        var dest = Path.Combine(_completionsDir, commandName + ".ps1");
        if (File.Exists(dest) && !force)
        {
            throw new CompleterExistsException(commandName, dest);
        }

        File.WriteAllText(dest, scriptContent);
        return dest;
    }

    public static string InferCommandName(string commandLine)
    {
        var token = FirstToken(commandLine).Trim().Trim('"').Trim('\'');
        if (string.IsNullOrWhiteSpace(token))
        {
            throw new InvalidCommandNameException(commandLine, "Could not infer a command name. Pass --name.");
        }

        var file = Path.GetFileName(token);
        var name = Path.GetFileNameWithoutExtension(file);
        if (string.IsNullOrWhiteSpace(name))
        {
            name = token;
        }

        CatalogManager.ValidateCommandName(name);
        return name;
    }

    private string CaptureHelpText(string commandLine)
    {
        var first = _runner.Run(AppendArg(commandLine, "--help"), TimeSpan.FromSeconds(30));
        var firstText = CombineOutput(first);
        if (HelpCompleterGenerator.HasSuggestions(firstText))
        {
            return firstText;
        }

        var second = _runner.Run(AppendArg(commandLine, "-h"), TimeSpan.FromSeconds(30));
        var secondText = CombineOutput(second);
        if (HelpCompleterGenerator.HasSuggestions(secondText))
        {
            return secondText;
        }

        throw new CompleterEmptyException(
            $"No flags or subcommands were found in --help/-h output for '{commandLine}'.");
    }

    private static string CombineOutput(CommandCapture result)
        => (result.StandardOutput ?? "") + Environment.NewLine + (result.StandardError ?? "");

    private static string AppendArg(string commandLine, string arg)
        => string.IsNullOrWhiteSpace(commandLine) ? arg : commandLine.TrimEnd() + " " + arg;

    private static string FirstToken(string commandLine)
    {
        var text = commandLine.Trim();
        if (text.Length == 0)
        {
            return "";
        }

        if (text[0] is '"' or '\'')
        {
            var quote = text[0];
            var end = text.IndexOf(quote, 1);
            return end > 0 ? text[1..end] : text.Trim(quote);
        }

        var space = text.IndexOf(' ');
        return space < 0 ? text : text[..space];
    }
}
