using System;
using System.IO;
using PathManager.Core.Env;
using PathManager.Core.Exceptions;

namespace PathManager.Core.Complete;

public class CompletionManager
{
    private readonly IEnvironmentProvider _env;
    private readonly string _completionsDir;

    public string CompletionsDirectory => _completionsDir;

    public CompletionManager(IEnvironmentProvider env)
    {
        _env = env ?? throw new ArgumentNullException(nameof(env));
        _completionsDir = Path.Combine(_env.GetPmHome(), "completions");
        Directory.CreateDirectory(_completionsDir);
    }

    public string GetHookScript()
    {
        var pmHome = _env.GetPmHome();
        var shimsDir = Path.Combine(pmHome, "shims");
        var compsDir = _completionsDir;

        return $@"# >>> PathManager Initialization >>>
# Automatically generated by PathManager. Do not edit manually.
$pmShimDir = ""{shimsDir}""
if (Test-Path $pmShimDir) {{
    if ($env:PATH -notlike ""$pmShimDir;*"") {{
        $env:PATH = ""$pmShimDir;$env:PATH""
    }}
}}

$pmCompDir = ""{compsDir}""
if (Test-Path $pmCompDir) {{
    Get-ChildItem -Path $pmCompDir -Filter ""*.ps1"" -File -ErrorAction SilentlyContinue | ForEach-Object {{
        . $_.FullName
    }}
}}

# Native Argument Completer for pathman CLI
if (Get-Command Register-ArgumentCompleter -ErrorAction SilentlyContinue) {{
    Register-ArgumentCompleter -Native -CommandName pathman -ScriptBlock {{
        param($wordToComplete, $commandAst, $cursorPosition)
        $elements = $commandAst.CommandElements
        $verbs = @('link', 'unlink', 'list', 'why', 'doctor', 'path', 'undo', 'completions', 'uninstall', 'upgrade')
        $flags = @('--json', '--help', '-h', '--version', '-v')

        if ($elements.Count -le 2) {{
            return ($verbs + $flags) | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }}
        }}

        $verb = $elements[1].Value
        switch ($verb) {{
            'link' {{
                $linkFlags = @('--force', '--host', '--i-trust-this', '--json')
                return $linkFlags | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'path' {{
                $pathSub = @('add', 'remove')
                return $pathSub | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'doctor' {{
                $docFlags = @('--repair', '--json')
                return $docFlags | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'completions' {{
                $compSub = @('install')
                return $compSub | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
            'uninstall' {{
                $unFlags = @('--keep-shims', '--json')
                return $unFlags | Where-Object {{ $_ -like ""$wordToComplete*"" }} | ForEach-Object {{
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }}
            }}
        }}
    }}
}}
# <<< PathManager Initialization <<<
";
    }

    public string InstallHook(bool windowsPowerShell = false)
    {
        var userProfile = _env.GetUserProfile();
        var profileDir = windowsPowerShell
            ? Path.Combine(userProfile, "Documents", "WindowsPowerShell")
            : Path.Combine(userProfile, "Documents", "PowerShell");

        var profilePath = Path.Combine(profileDir, "Microsoft.PowerShell_profile.ps1");
        var hook = GetHookScript();

        try
        {
            Directory.CreateDirectory(profileDir);

            var existingContent = File.Exists(profilePath) ? File.ReadAllText(profilePath) : "";
            if (existingContent.Contains("# >>> PathManager Initialization >>>"))
            {
                // Replace existing block
                var startIdx = existingContent.IndexOf("# >>> PathManager Initialization >>>", StringComparison.Ordinal);
                var endMarker = "# <<< PathManager Initialization <<<";
                var endIdx = existingContent.IndexOf(endMarker, StringComparison.Ordinal);
                if (endIdx != -1)
                {
                    endIdx += endMarker.Length;
                    existingContent = existingContent.Remove(startIdx, endIdx - startIdx).Trim();
                }
            }

            var updatedContent = string.IsNullOrWhiteSpace(existingContent)
                ? hook
                : existingContent.TrimEnd() + System.Environment.NewLine + System.Environment.NewLine + hook;

            File.WriteAllText(profilePath, updatedContent);
            return profilePath;
        }
        catch (Exception ex)
        {
            throw new ProfileWriteFailedException(profilePath, hook, ex);
        }
    }

    public void AddCompletionFile(string commandName, string scriptContent)
    {
        var path = Path.Combine(_completionsDir, commandName + ".ps1");
        File.WriteAllText(path, scriptContent);
    }

    public bool RemoveCompletionFile(string commandName)
    {
        var path = Path.Combine(_completionsDir, commandName + ".ps1");
        if (File.Exists(path))
        {
            File.Delete(path);
            return true;
        }
        return false;
    }
}
