using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using PathManager.Core.Exceptions;

namespace PathManager.Core.Complete;

public static class HelpCompleterGenerator
{
    private static readonly Regex LongFlag = new(@"--[A-Za-z][\w-]*", RegexOptions.Compiled);
    private static readonly Regex ShortFlag = new(@"(?<![A-Za-z0-9-])-[A-Za-z](?![A-Za-z0-9])", RegexOptions.Compiled);
    private static readonly Regex CommandsHeader = new(@"^\s*(?:commands|subcommands|available commands)\s*:?\s*$", RegexOptions.IgnoreCase | RegexOptions.Compiled);
    private static readonly Regex SubcommandLine = new(@"^\s{2,}([A-Za-z][\w-]*)\s{2,}\S", RegexOptions.Compiled);

    public static IReadOnlyList<string> ExtractSuggestions(string helpText)
    {
        if (string.IsNullOrWhiteSpace(helpText))
        {
            return Array.Empty<string>();
        }

        var seen = new HashSet<string>(StringComparer.Ordinal);
        var suggestions = new List<string>();

        void Add(string token)
        {
            if (seen.Add(token))
            {
                suggestions.Add(token);
            }
        }

        foreach (Match match in LongFlag.Matches(helpText))
        {
            Add(match.Value);
        }

        foreach (Match match in ShortFlag.Matches(helpText))
        {
            Add(match.Value);
        }

        foreach (var sub in ExtractSubcommands(helpText))
        {
            Add(sub);
        }

        return suggestions;
    }

    public static bool HasSuggestions(string helpText) => ExtractSuggestions(helpText).Count > 0;

    public static string Generate(string commandName, string helpText)
    {
        var suggestions = ExtractSuggestions(helpText);
        if (suggestions.Count == 0)
        {
            throw new CompleterEmptyException(
                $"No flags or subcommands were found in --help output for '{commandName}'. Use register-file or register-command instead.");
        }

        var escapedName = commandName.Replace("'", "''", StringComparison.Ordinal);
        var items = string.Join(", ", suggestions.Select(s => "'" + s.Replace("'", "''", StringComparison.Ordinal) + "'"));

        var sb = new StringBuilder();
        sb.AppendLine($"# Generated by pathman completions from-help for {commandName}");
        sb.AppendLine("if (Get-Command Register-ArgumentCompleter -ErrorAction SilentlyContinue) {");
        sb.AppendLine($"    Register-ArgumentCompleter -Native -CommandName '{escapedName}' -ScriptBlock {{");
        sb.AppendLine("        param($wordToComplete, $commandAst, $cursorPosition)");
        sb.AppendLine($"        $suggestions = @({items})");
        sb.AppendLine("        $suggestions | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {");
        sb.AppendLine("            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static IEnumerable<string> ExtractSubcommands(string helpText)
    {
        var lines = helpText.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var inCommands = false;
        foreach (var line in lines)
        {
            if (CommandsHeader.IsMatch(line))
            {
                inCommands = true;
                continue;
            }

            if (!inCommands)
            {
                continue;
            }

            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            if (line.Length > 0 && !char.IsWhiteSpace(line[0]) && line.TrimEnd().EndsWith(':'))
            {
                yield break;
            }

            var match = SubcommandLine.Match(line);
            if (match.Success)
            {
                yield return match.Groups[1].Value;
            }
        }
    }
}
