<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PathManager.Core</RootNamespace>
    <AssemblyName>PathManager.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
